### ISSUE TITLE
yum install fontconfig not working

### ISSUE THREAD

**Issue by KrishKayc** [lambci/yumda#4] opened 2019-12-18 10:59 UTC
I am using aws lambda for nodejs 12. There is no fontconfig installed in amazon linux 2.

So we used yumda to install the fontconfig package.

But, when we run the fc-list inside the bin directory, we get incorrect "error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory"

Please help.

**Comment by mhart** [comment] 2019-12-18 15:06
`fc-list` works fine for me.

EDIT: it outputs nothing on `nodejs12.x` or one of the other newer runtimes

Are you sure you're creating the lambda layer correctly?

**Comment by mhart** [comment] 2019-12-18 15:07
Sorry, just updated the comment – I was trying on an older runtime. On one of the newer runtimes it works fine, but outputs nothing because there are no fonts. I don't see any error though

**Comment by mhart** [comment] 2019-12-18 15:12
Here are the steps to verify if you'd like to check locally:

```
mkdir layer
docker run --rm -v "$PWD/layer":/lambda/opt lambci/yumda:2 yum install -y fontconfig
docker run --rm -it -v "$PWD/layer":/opt --entrypoint bash lambci/lambda:nodejs12.x
```
Then when you're in the bash shell:
```
fc-list
```
It will output nothing, but it won't error.

**Comment by KrishKayc** [comment] 2019-12-19 13:20
Hi,

Following your previous comments, it worked.

But when running on the aws lambda with the same image lambci/lambda:nodejs12.x, it errors out.

I tried by adding the fontconfig bin folder to the $PATH of the lambda environment, but still didn't work.

It errors out throwing "error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory".

Surely I'm missing something for the lambda environment.

**Comment by mhart** [comment] 2019-12-19 14:00
What steps did you do to create your layer? And are you sure you'd using the correct ARN for the layer when you attach it to your function?

**Comment by mhart** [comment] 2019-12-19 14:08
@KrishKayc I'm happy to help walk you through the layer creation if the README isn't detailed enough.

Is there a particular reason you're trying to bundle fontconfig? Is there another piece of software you're using that depends on it?

**Comment by KrishKayc** [comment] 2019-12-20 03:43
@mhart Yes, there is a code which uses 'fc-list' command to list out all the fonts in the lambda environment. It was working with node8, after node12 upgrade, because of the fontconfig not available, it fails.

**Comment by mhart** [comment] 2019-12-20 03:59
I understand that – how are you creating the layer you're attaching to your nodejs12.x lambda?

**Comment by KrishKayc** [comment] 2019-12-20 04:11
functions:
    screenshot:
        handler: index.handler
        events:
            - http:
                path: screenshot
                method: get
                cors: true
    info:
        handler: info.handler
        events:
            - http:
                path: info
                method: get
                cors: true
        layers:
            - {Ref: DependenciesLambdaLayer}

layers:
  dependencies:
    path: dependencies
    package:
      artifact: dependencies.zip

**Comment by KrishKayc** [comment] 2019-12-20 04:14
@mhart : I haven't specified any ARN in the function, do I need to deploy the layer to AWS first and then specify the layer ARN in the function?

**Comment by mhart** [comment] 2019-12-20 15:05
No, if you're specifying your layer as a resource in your cloudformation, then that should create it for you – you're doing the right thing there.

I wonder how you created `dependencies.zip`? Does it have the results of using `lambci/yumda:2`? I just want to make sure you weren't using the version intended for older runtimes, which is `lambci/yumda:1`

**Comment by KrishKayc** [comment] 2019-12-24 09:53
yes, dependencies.zip created from lambci/yumda:2 only, not 1.

**Comment by mhart** [comment] 2019-12-24 16:25
And if you do:

```
unzip -l dependencies.zip | grep libfontconfig.so.1
```

What does it output?

**Comment by mhart** [comment] 2019-12-24 16:27
(I'm now wondering if it's an issue with the serverless framework and the way it deploys layers)

**Comment by mhart** [comment] 2019-12-24 17:32
No, it all works fine for me with the serverless framework. Here's my `serverless.yaml`:

```yaml
service: yumda-example

provider:
  name: aws
  runtime: nodejs12.x

package:
  individually: true
  exclude:
    - ./**

functions:
  hello-world:
    handler: hello-world/app.lambdaHandler
    package:
      include:
        - hello-world/**
    layers:
      - {Ref: DependenciesLambdaLayer}

layers:
  dependencies:
    path: dependencies
    package:
      artifact: dependencies.zip
```

And then my `app.js` looks like:

```js
const { execSync } = require('child_process')

exports.lambdaHandler = async(event, context) => {
  execSync('fc-list', { encoding: 'utf8', stdio: 'inherit' })
}
```

If I create a fresh `dependencies` directory, and then run this:

```console
docker run --rm -v "$PWD/dependencies":/lambda/opt lambci/yumda:2 yum install -y fontconfig
```

Then it executes ok locally:

```console
sls invoke local --docker -f hello-world
```

Then I zip up the dependencies:

```console
rm -f dependencies.zip && cd dependencies && zip -yr ../dependencies.zip . && cd ..
```

Then I deploy:

```console
sls deploy
```

Then once that completes I can invoke it remotely:

```console
sls invoke -f hello-world
```

This all works fine, with no errors

**Comment by mhart** [comment] 2020-04-05 14:45
@KrishKayc any update on this? I haven't been able to reproduce

**Comment by mhart** [comment] 2020-06-24 01:48
I'm going to close this as there have been no updates in a while

**Closed as completed by mhart** 2020-06-24 01:48 UTC
